# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

[[override]]
  name = "github.com/sirupsen/logrus"
  branch = "master"

[[constraint]]
  name = "github.com/thecodeteam/gocsi"
  version = "0.3.0"

[[constraint]]
  name = "github.com/thecodeteam/gofsutil"
  version = "0.1.0"

[[override]]
  name = "github.com/container-storage-interface/spec"
  version = "0.1.0"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.7.3"
