# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.2"

[[constraint]]
  name = "golang.org/x/net"
  branch = "master"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.5.2"

[[constraint]]
  name = "github.com/codedellemc/gocsi"
  revision = "00d5dd1afec2c204bf084a552685888c821ed445"

[[constraint]]
  name = "github.com/codedellemc/goioc"
  version = "0.1.1"

[[constraint]]
  name = "github.com/codedellemc/csi-blockdevices"
  revision = "75415a68da56bbf234398937009dedfc45f4334d"
